-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity aes_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    in_V_ce0 : OUT STD_LOGIC;
    in_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    out_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_V_ce0 : OUT STD_LOGIC;
    out_V_we0 : OUT STD_LOGIC;
    out_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    w_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    w_V_ce0 : OUT STD_LOGIC;
    w_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of aes_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "aes_top,hls_ip_2020_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.453444,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=618,HLS_SYN_LUT=2258,HLS_VERSION=2020_1_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_Cipher_fu_16_ap_start : STD_LOGIC;
    signal grp_Cipher_fu_16_ap_done : STD_LOGIC;
    signal grp_Cipher_fu_16_ap_idle : STD_LOGIC;
    signal grp_Cipher_fu_16_ap_ready : STD_LOGIC;
    signal grp_Cipher_fu_16_in_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_fu_16_in_V_ce0 : STD_LOGIC;
    signal grp_Cipher_fu_16_out_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Cipher_fu_16_out_V_ce0 : STD_LOGIC;
    signal grp_Cipher_fu_16_out_V_we0 : STD_LOGIC;
    signal grp_Cipher_fu_16_out_V_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Cipher_fu_16_w_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_Cipher_fu_16_w_V_ce0 : STD_LOGIC;
    signal grp_Cipher_fu_16_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component Cipher IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        in_V_ce0 : OUT STD_LOGIC;
        in_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        out_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_V_ce0 : OUT STD_LOGIC;
        out_V_we0 : OUT STD_LOGIC;
        out_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        w_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        w_V_ce0 : OUT STD_LOGIC;
        w_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_Cipher_fu_16 : component Cipher
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_fu_16_ap_start,
        ap_done => grp_Cipher_fu_16_ap_done,
        ap_idle => grp_Cipher_fu_16_ap_idle,
        ap_ready => grp_Cipher_fu_16_ap_ready,
        in_V_address0 => grp_Cipher_fu_16_in_V_address0,
        in_V_ce0 => grp_Cipher_fu_16_in_V_ce0,
        in_V_q0 => in_V_q0,
        out_V_address0 => grp_Cipher_fu_16_out_V_address0,
        out_V_ce0 => grp_Cipher_fu_16_out_V_ce0,
        out_V_we0 => grp_Cipher_fu_16_out_V_we0,
        out_V_d0 => grp_Cipher_fu_16_out_V_d0,
        w_V_address0 => grp_Cipher_fu_16_w_V_address0,
        w_V_ce0 => grp_Cipher_fu_16_w_V_ce0,
        w_V_q0 => w_V_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_Cipher_fu_16_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Cipher_fu_16_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_Cipher_fu_16_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Cipher_fu_16_ap_ready = ap_const_logic_1)) then 
                    grp_Cipher_fu_16_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_Cipher_fu_16_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_Cipher_fu_16_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_done_assign_proc : process(grp_Cipher_fu_16_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_Cipher_fu_16_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_Cipher_fu_16_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_Cipher_fu_16_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_Cipher_fu_16_ap_start <= grp_Cipher_fu_16_ap_start_reg;
    in_V_address0 <= grp_Cipher_fu_16_in_V_address0;
    in_V_ce0 <= grp_Cipher_fu_16_in_V_ce0;
    out_V_address0 <= grp_Cipher_fu_16_out_V_address0;
    out_V_ce0 <= grp_Cipher_fu_16_out_V_ce0;
    out_V_d0 <= grp_Cipher_fu_16_out_V_d0;
    out_V_we0 <= grp_Cipher_fu_16_out_V_we0;
    w_V_address0 <= grp_Cipher_fu_16_w_V_address0;
    w_V_ce0 <= grp_Cipher_fu_16_w_V_ce0;
end behav;
