// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "aes_top.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic aes_top::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic aes_top::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> aes_top::ap_ST_fsm_state1 = "1";
const sc_lv<2> aes_top::ap_ST_fsm_state2 = "10";
const sc_lv<32> aes_top::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> aes_top::ap_const_lv32_1 = "1";
const bool aes_top::ap_const_boolean_1 = true;

aes_top::aes_top(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_Cipher_fu_16 = new Cipher("grp_Cipher_fu_16");
    grp_Cipher_fu_16->ap_clk(ap_clk);
    grp_Cipher_fu_16->ap_rst(ap_rst);
    grp_Cipher_fu_16->ap_start(grp_Cipher_fu_16_ap_start);
    grp_Cipher_fu_16->ap_done(grp_Cipher_fu_16_ap_done);
    grp_Cipher_fu_16->ap_idle(grp_Cipher_fu_16_ap_idle);
    grp_Cipher_fu_16->ap_ready(grp_Cipher_fu_16_ap_ready);
    grp_Cipher_fu_16->in_V_address0(grp_Cipher_fu_16_in_V_address0);
    grp_Cipher_fu_16->in_V_ce0(grp_Cipher_fu_16_in_V_ce0);
    grp_Cipher_fu_16->in_V_q0(in_V_q0);
    grp_Cipher_fu_16->out_V_address0(grp_Cipher_fu_16_out_V_address0);
    grp_Cipher_fu_16->out_V_ce0(grp_Cipher_fu_16_out_V_ce0);
    grp_Cipher_fu_16->out_V_we0(grp_Cipher_fu_16_out_V_we0);
    grp_Cipher_fu_16->out_V_d0(grp_Cipher_fu_16_out_V_d0);
    grp_Cipher_fu_16->w_V_address0(grp_Cipher_fu_16_w_V_address0);
    grp_Cipher_fu_16->w_V_ce0(grp_Cipher_fu_16_w_V_ce0);
    grp_Cipher_fu_16->w_V_q0(w_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( grp_Cipher_fu_16_ap_done );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_Cipher_fu_16_ap_done );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_Cipher_fu_16_ap_start);
    sensitive << ( grp_Cipher_fu_16_ap_start_reg );

    SC_METHOD(thread_in_V_address0);
    sensitive << ( grp_Cipher_fu_16_in_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_in_V_ce0);
    sensitive << ( grp_Cipher_fu_16_in_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_out_V_address0);
    sensitive << ( grp_Cipher_fu_16_out_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_out_V_ce0);
    sensitive << ( grp_Cipher_fu_16_out_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_out_V_d0);
    sensitive << ( grp_Cipher_fu_16_out_V_d0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_out_V_we0);
    sensitive << ( grp_Cipher_fu_16_out_V_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_w_V_address0);
    sensitive << ( grp_Cipher_fu_16_w_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_w_V_ce0);
    sensitive << ( grp_Cipher_fu_16_w_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_Cipher_fu_16_ap_done );
    sensitive << ( ap_CS_fsm_state2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "01";
    grp_Cipher_fu_16_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "aes_top_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_V_address0, "(port)in_V_address0");
    sc_trace(mVcdFile, in_V_ce0, "(port)in_V_ce0");
    sc_trace(mVcdFile, in_V_q0, "(port)in_V_q0");
    sc_trace(mVcdFile, out_V_address0, "(port)out_V_address0");
    sc_trace(mVcdFile, out_V_ce0, "(port)out_V_ce0");
    sc_trace(mVcdFile, out_V_we0, "(port)out_V_we0");
    sc_trace(mVcdFile, out_V_d0, "(port)out_V_d0");
    sc_trace(mVcdFile, w_V_address0, "(port)w_V_address0");
    sc_trace(mVcdFile, w_V_ce0, "(port)w_V_ce0");
    sc_trace(mVcdFile, w_V_q0, "(port)w_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_Cipher_fu_16_ap_start, "grp_Cipher_fu_16_ap_start");
    sc_trace(mVcdFile, grp_Cipher_fu_16_ap_done, "grp_Cipher_fu_16_ap_done");
    sc_trace(mVcdFile, grp_Cipher_fu_16_ap_idle, "grp_Cipher_fu_16_ap_idle");
    sc_trace(mVcdFile, grp_Cipher_fu_16_ap_ready, "grp_Cipher_fu_16_ap_ready");
    sc_trace(mVcdFile, grp_Cipher_fu_16_in_V_address0, "grp_Cipher_fu_16_in_V_address0");
    sc_trace(mVcdFile, grp_Cipher_fu_16_in_V_ce0, "grp_Cipher_fu_16_in_V_ce0");
    sc_trace(mVcdFile, grp_Cipher_fu_16_out_V_address0, "grp_Cipher_fu_16_out_V_address0");
    sc_trace(mVcdFile, grp_Cipher_fu_16_out_V_ce0, "grp_Cipher_fu_16_out_V_ce0");
    sc_trace(mVcdFile, grp_Cipher_fu_16_out_V_we0, "grp_Cipher_fu_16_out_V_we0");
    sc_trace(mVcdFile, grp_Cipher_fu_16_out_V_d0, "grp_Cipher_fu_16_out_V_d0");
    sc_trace(mVcdFile, grp_Cipher_fu_16_w_V_address0, "grp_Cipher_fu_16_w_V_address0");
    sc_trace(mVcdFile, grp_Cipher_fu_16_w_V_ce0, "grp_Cipher_fu_16_w_V_ce0");
    sc_trace(mVcdFile, grp_Cipher_fu_16_ap_start_reg, "grp_Cipher_fu_16_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("aes_top.hdltvin.dat");
    mHdltvoutHandle.open("aes_top.hdltvout.dat");
}

aes_top::~aes_top() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_Cipher_fu_16;
}

void aes_top::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_Cipher_fu_16_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_Cipher_fu_16_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Cipher_fu_16_ap_ready.read())) {
            grp_Cipher_fu_16_ap_start_reg = ap_const_logic_0;
        }
    }
}

void aes_top::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void aes_top::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void aes_top::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(grp_Cipher_fu_16_ap_done.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void aes_top::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void aes_top::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(grp_Cipher_fu_16_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void aes_top::thread_grp_Cipher_fu_16_ap_start() {
    grp_Cipher_fu_16_ap_start = grp_Cipher_fu_16_ap_start_reg.read();
}

void aes_top::thread_in_V_address0() {
    in_V_address0 = grp_Cipher_fu_16_in_V_address0.read();
}

void aes_top::thread_in_V_ce0() {
    in_V_ce0 = grp_Cipher_fu_16_in_V_ce0.read();
}

void aes_top::thread_out_V_address0() {
    out_V_address0 = grp_Cipher_fu_16_out_V_address0.read();
}

void aes_top::thread_out_V_ce0() {
    out_V_ce0 = grp_Cipher_fu_16_out_V_ce0.read();
}

void aes_top::thread_out_V_d0() {
    out_V_d0 = grp_Cipher_fu_16_out_V_d0.read();
}

void aes_top::thread_out_V_we0() {
    out_V_we0 = grp_Cipher_fu_16_out_V_we0.read();
}

void aes_top::thread_w_V_address0() {
    w_V_address0 = grp_Cipher_fu_16_w_V_address0.read();
}

void aes_top::thread_w_V_ce0() {
    w_V_ce0 = grp_Cipher_fu_16_w_V_ce0.read();
}

void aes_top::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_Cipher_fu_16_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

void aes_top::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_V_address0\" :  \"" << in_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_V_ce0\" :  \"" << in_V_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_V_q0\" :  \"" << in_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_V_address0\" :  \"" << out_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_V_ce0\" :  \"" << out_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_V_we0\" :  \"" << out_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_V_d0\" :  \"" << out_V_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"w_V_address0\" :  \"" << w_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"w_V_ce0\" :  \"" << w_V_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"w_V_q0\" :  \"" << w_V_q0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

