// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "MixColumns.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic MixColumns::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic MixColumns::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> MixColumns::ap_ST_fsm_state1 = "1";
const sc_lv<6> MixColumns::ap_ST_fsm_state2 = "10";
const sc_lv<6> MixColumns::ap_ST_fsm_state3 = "100";
const sc_lv<6> MixColumns::ap_ST_fsm_state4 = "1000";
const sc_lv<6> MixColumns::ap_ST_fsm_state5 = "10000";
const sc_lv<6> MixColumns::ap_ST_fsm_state6 = "100000";
const sc_lv<32> MixColumns::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> MixColumns::ap_const_lv32_1 = "1";
const sc_lv<1> MixColumns::ap_const_lv1_0 = "0";
const sc_lv<32> MixColumns::ap_const_lv32_2 = "10";
const sc_lv<1> MixColumns::ap_const_lv1_1 = "1";
const sc_lv<32> MixColumns::ap_const_lv32_4 = "100";
const bool MixColumns::ap_const_boolean_0 = false;
const sc_lv<32> MixColumns::ap_const_lv32_5 = "101";
const sc_lv<3> MixColumns::ap_const_lv3_0 = "000";
const sc_lv<32> MixColumns::ap_const_lv32_3 = "11";
const sc_lv<3> MixColumns::ap_const_lv3_2 = "10";
const sc_lv<3> MixColumns::ap_const_lv3_3 = "11";
const sc_lv<2> MixColumns::ap_const_lv2_0 = "00";
const sc_lv<2> MixColumns::ap_const_lv2_1 = "1";
const sc_lv<2> MixColumns::ap_const_lv2_2 = "10";
const sc_lv<2> MixColumns::ap_const_lv2_3 = "11";
const sc_lv<3> MixColumns::ap_const_lv3_4 = "100";
const sc_lv<3> MixColumns::ap_const_lv3_1 = "1";
const bool MixColumns::ap_const_boolean_1 = true;

MixColumns::MixColumns(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_gmul_fu_102 = new gmul("grp_gmul_fu_102");
    grp_gmul_fu_102->ap_clk(ap_clk);
    grp_gmul_fu_102->ap_rst(ap_rst);
    grp_gmul_fu_102->ap_start(grp_gmul_fu_102_ap_start);
    grp_gmul_fu_102->ap_done(grp_gmul_fu_102_ap_done);
    grp_gmul_fu_102->ap_idle(grp_gmul_fu_102_ap_idle);
    grp_gmul_fu_102->ap_ready(grp_gmul_fu_102_ap_ready);
    grp_gmul_fu_102->a_V(ap_var_for_const0);
    grp_gmul_fu_102->b_V(lhs_V_1_fu_32);
    grp_gmul_fu_102->ap_return(grp_gmul_fu_102_ap_return);
    grp_gmul_fu_109 = new gmul("grp_gmul_fu_109");
    grp_gmul_fu_109->ap_clk(ap_clk);
    grp_gmul_fu_109->ap_rst(ap_rst);
    grp_gmul_fu_109->ap_start(grp_gmul_fu_109_ap_start);
    grp_gmul_fu_109->ap_done(grp_gmul_fu_109_ap_done);
    grp_gmul_fu_109->ap_idle(grp_gmul_fu_109_ap_idle);
    grp_gmul_fu_109->ap_ready(grp_gmul_fu_109_ap_ready);
    grp_gmul_fu_109->a_V(ap_var_for_const1);
    grp_gmul_fu_109->b_V(rhs_V_1_fu_36);
    grp_gmul_fu_109->ap_return(grp_gmul_fu_109_ap_return);
    grp_gmul_fu_116 = new gmul("grp_gmul_fu_116");
    grp_gmul_fu_116->ap_clk(ap_clk);
    grp_gmul_fu_116->ap_rst(ap_rst);
    grp_gmul_fu_116->ap_start(grp_gmul_fu_116_ap_start);
    grp_gmul_fu_116->ap_done(grp_gmul_fu_116_ap_done);
    grp_gmul_fu_116->ap_idle(grp_gmul_fu_116_ap_idle);
    grp_gmul_fu_116->ap_ready(grp_gmul_fu_116_ap_ready);
    grp_gmul_fu_116->a_V(ap_var_for_const0);
    grp_gmul_fu_116->b_V(rhs_V_1_fu_36);
    grp_gmul_fu_116->ap_return(grp_gmul_fu_116_ap_return);
    grp_gmul_fu_123 = new gmul("grp_gmul_fu_123");
    grp_gmul_fu_123->ap_clk(ap_clk);
    grp_gmul_fu_123->ap_rst(ap_rst);
    grp_gmul_fu_123->ap_start(grp_gmul_fu_123_ap_start);
    grp_gmul_fu_123->ap_done(grp_gmul_fu_123_ap_done);
    grp_gmul_fu_123->ap_idle(grp_gmul_fu_123_ap_idle);
    grp_gmul_fu_123->ap_ready(grp_gmul_fu_123_ap_ready);
    grp_gmul_fu_123->a_V(ap_var_for_const1);
    grp_gmul_fu_123->b_V(rhs_V_2_fu_40);
    grp_gmul_fu_123->ap_return(grp_gmul_fu_123_ap_return);
    grp_gmul_fu_130 = new gmul("grp_gmul_fu_130");
    grp_gmul_fu_130->ap_clk(ap_clk);
    grp_gmul_fu_130->ap_rst(ap_rst);
    grp_gmul_fu_130->ap_start(grp_gmul_fu_130_ap_start);
    grp_gmul_fu_130->ap_done(grp_gmul_fu_130_ap_done);
    grp_gmul_fu_130->ap_idle(grp_gmul_fu_130_ap_idle);
    grp_gmul_fu_130->ap_ready(grp_gmul_fu_130_ap_ready);
    grp_gmul_fu_130->a_V(ap_var_for_const0);
    grp_gmul_fu_130->b_V(rhs_V_2_fu_40);
    grp_gmul_fu_130->ap_return(grp_gmul_fu_130_ap_return);
    grp_gmul_fu_137 = new gmul("grp_gmul_fu_137");
    grp_gmul_fu_137->ap_clk(ap_clk);
    grp_gmul_fu_137->ap_rst(ap_rst);
    grp_gmul_fu_137->ap_start(grp_gmul_fu_137_ap_start);
    grp_gmul_fu_137->ap_done(grp_gmul_fu_137_ap_done);
    grp_gmul_fu_137->ap_idle(grp_gmul_fu_137_ap_idle);
    grp_gmul_fu_137->ap_ready(grp_gmul_fu_137_ap_ready);
    grp_gmul_fu_137->a_V(ap_var_for_const1);
    grp_gmul_fu_137->b_V(rhs_V_5_fu_44);
    grp_gmul_fu_137->ap_return(grp_gmul_fu_137_ap_return);
    grp_gmul_fu_144 = new gmul("grp_gmul_fu_144");
    grp_gmul_fu_144->ap_clk(ap_clk);
    grp_gmul_fu_144->ap_rst(ap_rst);
    grp_gmul_fu_144->ap_start(grp_gmul_fu_144_ap_start);
    grp_gmul_fu_144->ap_done(grp_gmul_fu_144_ap_done);
    grp_gmul_fu_144->ap_idle(grp_gmul_fu_144_ap_idle);
    grp_gmul_fu_144->ap_ready(grp_gmul_fu_144_ap_ready);
    grp_gmul_fu_144->a_V(ap_var_for_const1);
    grp_gmul_fu_144->b_V(lhs_V_1_fu_32);
    grp_gmul_fu_144->ap_return(grp_gmul_fu_144_ap_return);
    grp_gmul_fu_151 = new gmul("grp_gmul_fu_151");
    grp_gmul_fu_151->ap_clk(ap_clk);
    grp_gmul_fu_151->ap_rst(ap_rst);
    grp_gmul_fu_151->ap_start(grp_gmul_fu_151_ap_start);
    grp_gmul_fu_151->ap_done(grp_gmul_fu_151_ap_done);
    grp_gmul_fu_151->ap_idle(grp_gmul_fu_151_ap_idle);
    grp_gmul_fu_151->ap_ready(grp_gmul_fu_151_ap_ready);
    grp_gmul_fu_151->a_V(ap_var_for_const0);
    grp_gmul_fu_151->b_V(rhs_V_5_fu_44);
    grp_gmul_fu_151->ap_return(grp_gmul_fu_151_ap_return);
    aes_top_mux_42_8_bkb_U9 = new aes_top_mux_42_8_bkb<1,1,8,8,8,8,2,8>("aes_top_mux_42_8_bkb_U9");
    aes_top_mux_42_8_bkb_U9->din0(ret_V_reg_452);
    aes_top_mux_42_8_bkb_U9->din1(ret_V_1_reg_457);
    aes_top_mux_42_8_bkb_U9->din2(ret_V_2_reg_462);
    aes_top_mux_42_8_bkb_U9->din3(ret_V_3_reg_467);
    aes_top_mux_42_8_bkb_U9->din4(tmp_fu_354_p5);
    aes_top_mux_42_8_bkb_U9->dout(tmp_fu_354_p6);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln321_1_fu_340_p2);
    sensitive << ( zext_ln99_reg_397 );
    sensitive << ( zext_ln321_2_fu_336_p1 );

    SC_METHOD(thread_add_ln321_fu_198_p2);
    sensitive << ( zext_ln99_reg_397 );
    sensitive << ( zext_ln321_fu_194_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state5_on_subcall_done);
    sensitive << ( grp_gmul_fu_102_ap_done );
    sensitive << ( grp_gmul_fu_109_ap_done );
    sensitive << ( grp_gmul_fu_116_ap_done );
    sensitive << ( grp_gmul_fu_123_ap_done );
    sensitive << ( grp_gmul_fu_130_ap_done );
    sensitive << ( grp_gmul_fu_137_ap_done );
    sensitive << ( grp_gmul_fu_144_ap_done );
    sensitive << ( grp_gmul_fu_151_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln97_fu_158_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln97_fu_158_p2 );

    SC_METHOD(thread_c_fu_164_p2);
    sensitive << ( c_0_reg_69 );

    SC_METHOD(thread_grp_gmul_fu_102_ap_start);
    sensitive << ( grp_gmul_fu_102_ap_start_reg );

    SC_METHOD(thread_grp_gmul_fu_109_ap_start);
    sensitive << ( grp_gmul_fu_109_ap_start_reg );

    SC_METHOD(thread_grp_gmul_fu_116_ap_start);
    sensitive << ( grp_gmul_fu_116_ap_start_reg );

    SC_METHOD(thread_grp_gmul_fu_123_ap_start);
    sensitive << ( grp_gmul_fu_123_ap_start_reg );

    SC_METHOD(thread_grp_gmul_fu_130_ap_start);
    sensitive << ( grp_gmul_fu_130_ap_start_reg );

    SC_METHOD(thread_grp_gmul_fu_137_ap_start);
    sensitive << ( grp_gmul_fu_137_ap_start_reg );

    SC_METHOD(thread_grp_gmul_fu_144_ap_start);
    sensitive << ( grp_gmul_fu_144_ap_start_reg );

    SC_METHOD(thread_grp_gmul_fu_151_ap_start);
    sensitive << ( grp_gmul_fu_151_ap_start_reg );

    SC_METHOD(thread_icmp_ln106_fu_316_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( r2_0_reg_91 );

    SC_METHOD(thread_icmp_ln97_fu_158_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( c_0_reg_69 );

    SC_METHOD(thread_icmp_ln99_fu_174_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( r_0_reg_80 );

    SC_METHOD(thread_r_1_fu_322_p2);
    sensitive << ( r2_0_reg_91 );

    SC_METHOD(thread_r_fu_180_p2);
    sensitive << ( r_0_reg_80 );

    SC_METHOD(thread_ret_V_1_fu_278_p2);
    sensitive << ( xor_ln1357_4_fu_272_p2 );
    sensitive << ( xor_ln1357_3_fu_268_p2 );

    SC_METHOD(thread_ret_V_2_fu_294_p2);
    sensitive << ( xor_ln1357_7_fu_288_p2 );
    sensitive << ( xor_ln1357_6_fu_284_p2 );

    SC_METHOD(thread_ret_V_3_fu_310_p2);
    sensitive << ( xor_ln1357_10_fu_304_p2 );
    sensitive << ( xor_ln1357_9_fu_300_p2 );

    SC_METHOD(thread_ret_V_fu_262_p2);
    sensitive << ( xor_ln1357_1_fu_258_p2 );
    sensitive << ( xor_ln1357_fu_252_p2 );

    SC_METHOD(thread_state_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln321_1_fu_203_p1 );
    sensitive << ( zext_ln321_3_fu_345_p1 );

    SC_METHOD(thread_state_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_state_V_d0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_fu_354_p6 );

    SC_METHOD(thread_state_V_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln106_fu_316_p2 );

    SC_METHOD(thread_tmp_4_fu_186_p3);
    sensitive << ( r_0_reg_80 );

    SC_METHOD(thread_tmp_5_fu_328_p3);
    sensitive << ( r2_0_reg_91 );

    SC_METHOD(thread_tmp_fu_354_p5);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( r2_0_reg_91 );

    SC_METHOD(thread_trunc_ln321_fu_208_p1);
    sensitive << ( r_0_reg_80 );

    SC_METHOD(thread_xor_ln1357_10_fu_304_p2);
    sensitive << ( grp_gmul_fu_144_ap_return );
    sensitive << ( grp_gmul_fu_151_ap_return );

    SC_METHOD(thread_xor_ln1357_1_fu_258_p2);
    sensitive << ( rhs_V_2_fu_40 );
    sensitive << ( rhs_V_5_fu_44 );

    SC_METHOD(thread_xor_ln1357_3_fu_268_p2);
    sensitive << ( lhs_V_1_fu_32 );
    sensitive << ( rhs_V_5_fu_44 );

    SC_METHOD(thread_xor_ln1357_4_fu_272_p2);
    sensitive << ( grp_gmul_fu_116_ap_return );
    sensitive << ( grp_gmul_fu_123_ap_return );

    SC_METHOD(thread_xor_ln1357_6_fu_284_p2);
    sensitive << ( lhs_V_1_fu_32 );
    sensitive << ( rhs_V_1_fu_36 );

    SC_METHOD(thread_xor_ln1357_7_fu_288_p2);
    sensitive << ( grp_gmul_fu_130_ap_return );
    sensitive << ( grp_gmul_fu_137_ap_return );

    SC_METHOD(thread_xor_ln1357_9_fu_300_p2);
    sensitive << ( rhs_V_1_fu_36 );
    sensitive << ( rhs_V_2_fu_40 );

    SC_METHOD(thread_xor_ln1357_fu_252_p2);
    sensitive << ( grp_gmul_fu_102_ap_return );
    sensitive << ( grp_gmul_fu_109_ap_return );

    SC_METHOD(thread_zext_ln321_1_fu_203_p1);
    sensitive << ( add_ln321_fu_198_p2 );

    SC_METHOD(thread_zext_ln321_2_fu_336_p1);
    sensitive << ( tmp_5_fu_328_p3 );

    SC_METHOD(thread_zext_ln321_3_fu_345_p1);
    sensitive << ( add_ln321_1_fu_340_p2 );

    SC_METHOD(thread_zext_ln321_fu_194_p1);
    sensitive << ( tmp_4_fu_186_p3 );

    SC_METHOD(thread_zext_ln99_fu_170_p1);
    sensitive << ( c_0_reg_69 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln97_fu_158_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln99_fu_174_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_block_state5_on_subcall_done );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln106_fu_316_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "000001";
    grp_gmul_fu_102_ap_start_reg = SC_LOGIC_0;
    grp_gmul_fu_109_ap_start_reg = SC_LOGIC_0;
    grp_gmul_fu_116_ap_start_reg = SC_LOGIC_0;
    grp_gmul_fu_123_ap_start_reg = SC_LOGIC_0;
    grp_gmul_fu_130_ap_start_reg = SC_LOGIC_0;
    grp_gmul_fu_137_ap_start_reg = SC_LOGIC_0;
    grp_gmul_fu_144_ap_start_reg = SC_LOGIC_0;
    grp_gmul_fu_151_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "MixColumns_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, state_V_address0, "(port)state_V_address0");
    sc_trace(mVcdFile, state_V_ce0, "(port)state_V_ce0");
    sc_trace(mVcdFile, state_V_we0, "(port)state_V_we0");
    sc_trace(mVcdFile, state_V_d0, "(port)state_V_d0");
    sc_trace(mVcdFile, state_V_q0, "(port)state_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, c_fu_164_p2, "c_fu_164_p2");
    sc_trace(mVcdFile, c_reg_392, "c_reg_392");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln99_fu_170_p1, "zext_ln99_fu_170_p1");
    sc_trace(mVcdFile, zext_ln99_reg_397, "zext_ln99_reg_397");
    sc_trace(mVcdFile, icmp_ln97_fu_158_p2, "icmp_ln97_fu_158_p2");
    sc_trace(mVcdFile, r_fu_180_p2, "r_fu_180_p2");
    sc_trace(mVcdFile, r_reg_406, "r_reg_406");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln99_fu_174_p2, "icmp_ln99_fu_174_p2");
    sc_trace(mVcdFile, trunc_ln321_fu_208_p1, "trunc_ln321_fu_208_p1");
    sc_trace(mVcdFile, trunc_ln321_reg_416, "trunc_ln321_reg_416");
    sc_trace(mVcdFile, ret_V_fu_262_p2, "ret_V_fu_262_p2");
    sc_trace(mVcdFile, ret_V_reg_452, "ret_V_reg_452");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_gmul_fu_102_ap_ready, "grp_gmul_fu_102_ap_ready");
    sc_trace(mVcdFile, grp_gmul_fu_102_ap_done, "grp_gmul_fu_102_ap_done");
    sc_trace(mVcdFile, grp_gmul_fu_109_ap_ready, "grp_gmul_fu_109_ap_ready");
    sc_trace(mVcdFile, grp_gmul_fu_109_ap_done, "grp_gmul_fu_109_ap_done");
    sc_trace(mVcdFile, grp_gmul_fu_116_ap_ready, "grp_gmul_fu_116_ap_ready");
    sc_trace(mVcdFile, grp_gmul_fu_116_ap_done, "grp_gmul_fu_116_ap_done");
    sc_trace(mVcdFile, grp_gmul_fu_123_ap_ready, "grp_gmul_fu_123_ap_ready");
    sc_trace(mVcdFile, grp_gmul_fu_123_ap_done, "grp_gmul_fu_123_ap_done");
    sc_trace(mVcdFile, grp_gmul_fu_130_ap_ready, "grp_gmul_fu_130_ap_ready");
    sc_trace(mVcdFile, grp_gmul_fu_130_ap_done, "grp_gmul_fu_130_ap_done");
    sc_trace(mVcdFile, grp_gmul_fu_137_ap_ready, "grp_gmul_fu_137_ap_ready");
    sc_trace(mVcdFile, grp_gmul_fu_137_ap_done, "grp_gmul_fu_137_ap_done");
    sc_trace(mVcdFile, grp_gmul_fu_144_ap_ready, "grp_gmul_fu_144_ap_ready");
    sc_trace(mVcdFile, grp_gmul_fu_144_ap_done, "grp_gmul_fu_144_ap_done");
    sc_trace(mVcdFile, grp_gmul_fu_151_ap_ready, "grp_gmul_fu_151_ap_ready");
    sc_trace(mVcdFile, grp_gmul_fu_151_ap_done, "grp_gmul_fu_151_ap_done");
    sc_trace(mVcdFile, ap_block_state5_on_subcall_done, "ap_block_state5_on_subcall_done");
    sc_trace(mVcdFile, ret_V_1_fu_278_p2, "ret_V_1_fu_278_p2");
    sc_trace(mVcdFile, ret_V_1_reg_457, "ret_V_1_reg_457");
    sc_trace(mVcdFile, ret_V_2_fu_294_p2, "ret_V_2_fu_294_p2");
    sc_trace(mVcdFile, ret_V_2_reg_462, "ret_V_2_reg_462");
    sc_trace(mVcdFile, ret_V_3_fu_310_p2, "ret_V_3_fu_310_p2");
    sc_trace(mVcdFile, ret_V_3_reg_467, "ret_V_3_reg_467");
    sc_trace(mVcdFile, r_1_fu_322_p2, "r_1_fu_322_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_gmul_fu_102_ap_start, "grp_gmul_fu_102_ap_start");
    sc_trace(mVcdFile, grp_gmul_fu_102_ap_idle, "grp_gmul_fu_102_ap_idle");
    sc_trace(mVcdFile, grp_gmul_fu_102_ap_return, "grp_gmul_fu_102_ap_return");
    sc_trace(mVcdFile, grp_gmul_fu_109_ap_start, "grp_gmul_fu_109_ap_start");
    sc_trace(mVcdFile, grp_gmul_fu_109_ap_idle, "grp_gmul_fu_109_ap_idle");
    sc_trace(mVcdFile, grp_gmul_fu_109_ap_return, "grp_gmul_fu_109_ap_return");
    sc_trace(mVcdFile, grp_gmul_fu_116_ap_start, "grp_gmul_fu_116_ap_start");
    sc_trace(mVcdFile, grp_gmul_fu_116_ap_idle, "grp_gmul_fu_116_ap_idle");
    sc_trace(mVcdFile, grp_gmul_fu_116_ap_return, "grp_gmul_fu_116_ap_return");
    sc_trace(mVcdFile, grp_gmul_fu_123_ap_start, "grp_gmul_fu_123_ap_start");
    sc_trace(mVcdFile, grp_gmul_fu_123_ap_idle, "grp_gmul_fu_123_ap_idle");
    sc_trace(mVcdFile, grp_gmul_fu_123_ap_return, "grp_gmul_fu_123_ap_return");
    sc_trace(mVcdFile, grp_gmul_fu_130_ap_start, "grp_gmul_fu_130_ap_start");
    sc_trace(mVcdFile, grp_gmul_fu_130_ap_idle, "grp_gmul_fu_130_ap_idle");
    sc_trace(mVcdFile, grp_gmul_fu_130_ap_return, "grp_gmul_fu_130_ap_return");
    sc_trace(mVcdFile, grp_gmul_fu_137_ap_start, "grp_gmul_fu_137_ap_start");
    sc_trace(mVcdFile, grp_gmul_fu_137_ap_idle, "grp_gmul_fu_137_ap_idle");
    sc_trace(mVcdFile, grp_gmul_fu_137_ap_return, "grp_gmul_fu_137_ap_return");
    sc_trace(mVcdFile, grp_gmul_fu_144_ap_start, "grp_gmul_fu_144_ap_start");
    sc_trace(mVcdFile, grp_gmul_fu_144_ap_idle, "grp_gmul_fu_144_ap_idle");
    sc_trace(mVcdFile, grp_gmul_fu_144_ap_return, "grp_gmul_fu_144_ap_return");
    sc_trace(mVcdFile, grp_gmul_fu_151_ap_start, "grp_gmul_fu_151_ap_start");
    sc_trace(mVcdFile, grp_gmul_fu_151_ap_idle, "grp_gmul_fu_151_ap_idle");
    sc_trace(mVcdFile, grp_gmul_fu_151_ap_return, "grp_gmul_fu_151_ap_return");
    sc_trace(mVcdFile, c_0_reg_69, "c_0_reg_69");
    sc_trace(mVcdFile, icmp_ln106_fu_316_p2, "icmp_ln106_fu_316_p2");
    sc_trace(mVcdFile, r_0_reg_80, "r_0_reg_80");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, r2_0_reg_91, "r2_0_reg_91");
    sc_trace(mVcdFile, grp_gmul_fu_102_ap_start_reg, "grp_gmul_fu_102_ap_start_reg");
    sc_trace(mVcdFile, grp_gmul_fu_109_ap_start_reg, "grp_gmul_fu_109_ap_start_reg");
    sc_trace(mVcdFile, grp_gmul_fu_116_ap_start_reg, "grp_gmul_fu_116_ap_start_reg");
    sc_trace(mVcdFile, grp_gmul_fu_123_ap_start_reg, "grp_gmul_fu_123_ap_start_reg");
    sc_trace(mVcdFile, grp_gmul_fu_130_ap_start_reg, "grp_gmul_fu_130_ap_start_reg");
    sc_trace(mVcdFile, grp_gmul_fu_137_ap_start_reg, "grp_gmul_fu_137_ap_start_reg");
    sc_trace(mVcdFile, grp_gmul_fu_144_ap_start_reg, "grp_gmul_fu_144_ap_start_reg");
    sc_trace(mVcdFile, grp_gmul_fu_151_ap_start_reg, "grp_gmul_fu_151_ap_start_reg");
    sc_trace(mVcdFile, zext_ln321_1_fu_203_p1, "zext_ln321_1_fu_203_p1");
    sc_trace(mVcdFile, zext_ln321_3_fu_345_p1, "zext_ln321_3_fu_345_p1");
    sc_trace(mVcdFile, lhs_V_1_fu_32, "lhs_V_1_fu_32");
    sc_trace(mVcdFile, rhs_V_1_fu_36, "rhs_V_1_fu_36");
    sc_trace(mVcdFile, rhs_V_2_fu_40, "rhs_V_2_fu_40");
    sc_trace(mVcdFile, rhs_V_5_fu_44, "rhs_V_5_fu_44");
    sc_trace(mVcdFile, tmp_fu_354_p6, "tmp_fu_354_p6");
    sc_trace(mVcdFile, tmp_4_fu_186_p3, "tmp_4_fu_186_p3");
    sc_trace(mVcdFile, zext_ln321_fu_194_p1, "zext_ln321_fu_194_p1");
    sc_trace(mVcdFile, add_ln321_fu_198_p2, "add_ln321_fu_198_p2");
    sc_trace(mVcdFile, xor_ln1357_1_fu_258_p2, "xor_ln1357_1_fu_258_p2");
    sc_trace(mVcdFile, xor_ln1357_fu_252_p2, "xor_ln1357_fu_252_p2");
    sc_trace(mVcdFile, xor_ln1357_4_fu_272_p2, "xor_ln1357_4_fu_272_p2");
    sc_trace(mVcdFile, xor_ln1357_3_fu_268_p2, "xor_ln1357_3_fu_268_p2");
    sc_trace(mVcdFile, xor_ln1357_7_fu_288_p2, "xor_ln1357_7_fu_288_p2");
    sc_trace(mVcdFile, xor_ln1357_6_fu_284_p2, "xor_ln1357_6_fu_284_p2");
    sc_trace(mVcdFile, xor_ln1357_10_fu_304_p2, "xor_ln1357_10_fu_304_p2");
    sc_trace(mVcdFile, xor_ln1357_9_fu_300_p2, "xor_ln1357_9_fu_300_p2");
    sc_trace(mVcdFile, tmp_5_fu_328_p3, "tmp_5_fu_328_p3");
    sc_trace(mVcdFile, zext_ln321_2_fu_336_p1, "zext_ln321_2_fu_336_p1");
    sc_trace(mVcdFile, add_ln321_1_fu_340_p2, "add_ln321_1_fu_340_p2");
    sc_trace(mVcdFile, tmp_fu_354_p5, "tmp_fu_354_p5");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

MixColumns::~MixColumns() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_gmul_fu_102;
    delete grp_gmul_fu_109;
    delete grp_gmul_fu_116;
    delete grp_gmul_fu_123;
    delete grp_gmul_fu_130;
    delete grp_gmul_fu_137;
    delete grp_gmul_fu_144;
    delete grp_gmul_fu_151;
    delete aes_top_mux_42_8_bkb_U9;
}

void MixColumns::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv3_2;
}

void MixColumns::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv3_3;
}

void MixColumns::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln106_fu_316_p2.read()))) {
        c_0_reg_69 = c_reg_392.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        c_0_reg_69 = ap_const_lv3_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_gmul_fu_102_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(icmp_ln99_fu_174_p2.read(), ap_const_lv1_1))) {
            grp_gmul_fu_102_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_gmul_fu_102_ap_ready.read())) {
            grp_gmul_fu_102_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_gmul_fu_109_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(icmp_ln99_fu_174_p2.read(), ap_const_lv1_1))) {
            grp_gmul_fu_109_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_gmul_fu_109_ap_ready.read())) {
            grp_gmul_fu_109_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_gmul_fu_116_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(icmp_ln99_fu_174_p2.read(), ap_const_lv1_1))) {
            grp_gmul_fu_116_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_gmul_fu_116_ap_ready.read())) {
            grp_gmul_fu_116_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_gmul_fu_123_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(icmp_ln99_fu_174_p2.read(), ap_const_lv1_1))) {
            grp_gmul_fu_123_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_gmul_fu_123_ap_ready.read())) {
            grp_gmul_fu_123_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_gmul_fu_130_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(icmp_ln99_fu_174_p2.read(), ap_const_lv1_1))) {
            grp_gmul_fu_130_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_gmul_fu_130_ap_ready.read())) {
            grp_gmul_fu_130_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_gmul_fu_137_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(icmp_ln99_fu_174_p2.read(), ap_const_lv1_1))) {
            grp_gmul_fu_137_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_gmul_fu_137_ap_ready.read())) {
            grp_gmul_fu_137_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_gmul_fu_144_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(icmp_ln99_fu_174_p2.read(), ap_const_lv1_1))) {
            grp_gmul_fu_144_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_gmul_fu_144_ap_ready.read())) {
            grp_gmul_fu_144_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_gmul_fu_151_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(icmp_ln99_fu_174_p2.read(), ap_const_lv1_1))) {
            grp_gmul_fu_151_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_gmul_fu_151_ap_ready.read())) {
            grp_gmul_fu_151_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_316_p2.read()))) {
        r2_0_reg_91 = r_1_fu_322_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_block_state5_on_subcall_done.read(), ap_const_boolean_0))) {
        r2_0_reg_91 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        r_0_reg_80 = r_reg_406.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln97_fu_158_p2.read(), ap_const_lv1_0))) {
        r_0_reg_80 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        c_reg_392 = c_fu_164_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,2,2>(trunc_ln321_reg_416.read(), ap_const_lv2_0))) {
        lhs_V_1_fu_32 = state_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        r_reg_406 = r_fu_180_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_block_state5_on_subcall_done.read(), ap_const_boolean_0))) {
        ret_V_1_reg_457 = ret_V_1_fu_278_p2.read();
        ret_V_2_reg_462 = ret_V_2_fu_294_p2.read();
        ret_V_3_reg_467 = ret_V_3_fu_310_p2.read();
        ret_V_reg_452 = ret_V_fu_262_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,2,2>(trunc_ln321_reg_416.read(), ap_const_lv2_1))) {
        rhs_V_1_fu_36 = state_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,2,2>(trunc_ln321_reg_416.read(), ap_const_lv2_2))) {
        rhs_V_2_fu_40 = state_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,2,2>(trunc_ln321_reg_416.read(), ap_const_lv2_3))) {
        rhs_V_5_fu_44 = state_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_174_p2.read()))) {
        trunc_ln321_reg_416 = trunc_ln321_fu_208_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln97_fu_158_p2.read(), ap_const_lv1_0))) {
        zext_ln99_reg_397 = zext_ln99_fu_170_p1.read();
    }
}

void MixColumns::thread_add_ln321_1_fu_340_p2() {
    add_ln321_1_fu_340_p2 = (!zext_ln321_2_fu_336_p1.read().is_01() || !zext_ln99_reg_397.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln321_2_fu_336_p1.read()) + sc_biguint<6>(zext_ln99_reg_397.read()));
}

void MixColumns::thread_add_ln321_fu_198_p2() {
    add_ln321_fu_198_p2 = (!zext_ln321_fu_194_p1.read().is_01() || !zext_ln99_reg_397.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln321_fu_194_p1.read()) + sc_biguint<6>(zext_ln99_reg_397.read()));
}

void MixColumns::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void MixColumns::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void MixColumns::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void MixColumns::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void MixColumns::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void MixColumns::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void MixColumns::thread_ap_block_state5_on_subcall_done() {
    ap_block_state5_on_subcall_done = (esl_seteq<1,1,1>(ap_const_logic_0, grp_gmul_fu_102_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_gmul_fu_109_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_gmul_fu_116_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_gmul_fu_123_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_gmul_fu_130_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_gmul_fu_137_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_gmul_fu_144_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_gmul_fu_151_ap_done.read()));
}

void MixColumns::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln97_fu_158_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void MixColumns::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void MixColumns::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_fu_158_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void MixColumns::thread_c_fu_164_p2() {
    c_fu_164_p2 = (!c_0_reg_69.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(c_0_reg_69.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void MixColumns::thread_grp_gmul_fu_102_ap_start() {
    grp_gmul_fu_102_ap_start = grp_gmul_fu_102_ap_start_reg.read();
}

void MixColumns::thread_grp_gmul_fu_109_ap_start() {
    grp_gmul_fu_109_ap_start = grp_gmul_fu_109_ap_start_reg.read();
}

void MixColumns::thread_grp_gmul_fu_116_ap_start() {
    grp_gmul_fu_116_ap_start = grp_gmul_fu_116_ap_start_reg.read();
}

void MixColumns::thread_grp_gmul_fu_123_ap_start() {
    grp_gmul_fu_123_ap_start = grp_gmul_fu_123_ap_start_reg.read();
}

void MixColumns::thread_grp_gmul_fu_130_ap_start() {
    grp_gmul_fu_130_ap_start = grp_gmul_fu_130_ap_start_reg.read();
}

void MixColumns::thread_grp_gmul_fu_137_ap_start() {
    grp_gmul_fu_137_ap_start = grp_gmul_fu_137_ap_start_reg.read();
}

void MixColumns::thread_grp_gmul_fu_144_ap_start() {
    grp_gmul_fu_144_ap_start = grp_gmul_fu_144_ap_start_reg.read();
}

void MixColumns::thread_grp_gmul_fu_151_ap_start() {
    grp_gmul_fu_151_ap_start = grp_gmul_fu_151_ap_start_reg.read();
}

void MixColumns::thread_icmp_ln106_fu_316_p2() {
    icmp_ln106_fu_316_p2 = (!r2_0_reg_91.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(r2_0_reg_91.read() == ap_const_lv3_4);
}

void MixColumns::thread_icmp_ln97_fu_158_p2() {
    icmp_ln97_fu_158_p2 = (!c_0_reg_69.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_69.read() == ap_const_lv3_4);
}

void MixColumns::thread_icmp_ln99_fu_174_p2() {
    icmp_ln99_fu_174_p2 = (!r_0_reg_80.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(r_0_reg_80.read() == ap_const_lv3_4);
}

void MixColumns::thread_r_1_fu_322_p2() {
    r_1_fu_322_p2 = (!r2_0_reg_91.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(r2_0_reg_91.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void MixColumns::thread_r_fu_180_p2() {
    r_fu_180_p2 = (!r_0_reg_80.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(r_0_reg_80.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void MixColumns::thread_ret_V_1_fu_278_p2() {
    ret_V_1_fu_278_p2 = (xor_ln1357_4_fu_272_p2.read() ^ xor_ln1357_3_fu_268_p2.read());
}

void MixColumns::thread_ret_V_2_fu_294_p2() {
    ret_V_2_fu_294_p2 = (xor_ln1357_7_fu_288_p2.read() ^ xor_ln1357_6_fu_284_p2.read());
}

void MixColumns::thread_ret_V_3_fu_310_p2() {
    ret_V_3_fu_310_p2 = (xor_ln1357_10_fu_304_p2.read() ^ xor_ln1357_9_fu_300_p2.read());
}

void MixColumns::thread_ret_V_fu_262_p2() {
    ret_V_fu_262_p2 = (xor_ln1357_1_fu_258_p2.read() ^ xor_ln1357_fu_252_p2.read());
}

void MixColumns::thread_state_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        state_V_address0 =  (sc_lv<4>) (zext_ln321_3_fu_345_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        state_V_address0 =  (sc_lv<4>) (zext_ln321_1_fu_203_p1.read());
    } else {
        state_V_address0 = "XXXX";
    }
}

void MixColumns::thread_state_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        state_V_ce0 = ap_const_logic_1;
    } else {
        state_V_ce0 = ap_const_logic_0;
    }
}

void MixColumns::thread_state_V_d0() {
    state_V_d0 = tmp_fu_354_p6.read();
}

void MixColumns::thread_state_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_316_p2.read()))) {
        state_V_we0 = ap_const_logic_1;
    } else {
        state_V_we0 = ap_const_logic_0;
    }
}

void MixColumns::thread_tmp_4_fu_186_p3() {
    tmp_4_fu_186_p3 = esl_concat<3,2>(r_0_reg_80.read(), ap_const_lv2_0);
}

void MixColumns::thread_tmp_5_fu_328_p3() {
    tmp_5_fu_328_p3 = esl_concat<3,2>(r2_0_reg_91.read(), ap_const_lv2_0);
}

void MixColumns::thread_tmp_fu_354_p5() {
    tmp_fu_354_p5 = r2_0_reg_91.read().range(2-1, 0);
}

void MixColumns::thread_trunc_ln321_fu_208_p1() {
    trunc_ln321_fu_208_p1 = r_0_reg_80.read().range(2-1, 0);
}

void MixColumns::thread_xor_ln1357_10_fu_304_p2() {
    xor_ln1357_10_fu_304_p2 = (grp_gmul_fu_144_ap_return.read() ^ grp_gmul_fu_151_ap_return.read());
}

void MixColumns::thread_xor_ln1357_1_fu_258_p2() {
    xor_ln1357_1_fu_258_p2 = (rhs_V_2_fu_40.read() ^ rhs_V_5_fu_44.read());
}

void MixColumns::thread_xor_ln1357_3_fu_268_p2() {
    xor_ln1357_3_fu_268_p2 = (rhs_V_5_fu_44.read() ^ lhs_V_1_fu_32.read());
}

void MixColumns::thread_xor_ln1357_4_fu_272_p2() {
    xor_ln1357_4_fu_272_p2 = (grp_gmul_fu_116_ap_return.read() ^ grp_gmul_fu_123_ap_return.read());
}

void MixColumns::thread_xor_ln1357_6_fu_284_p2() {
    xor_ln1357_6_fu_284_p2 = (rhs_V_1_fu_36.read() ^ lhs_V_1_fu_32.read());
}

void MixColumns::thread_xor_ln1357_7_fu_288_p2() {
    xor_ln1357_7_fu_288_p2 = (grp_gmul_fu_130_ap_return.read() ^ grp_gmul_fu_137_ap_return.read());
}

void MixColumns::thread_xor_ln1357_9_fu_300_p2() {
    xor_ln1357_9_fu_300_p2 = (rhs_V_2_fu_40.read() ^ rhs_V_1_fu_36.read());
}

void MixColumns::thread_xor_ln1357_fu_252_p2() {
    xor_ln1357_fu_252_p2 = (grp_gmul_fu_109_ap_return.read() ^ grp_gmul_fu_102_ap_return.read());
}

void MixColumns::thread_zext_ln321_1_fu_203_p1() {
    zext_ln321_1_fu_203_p1 = esl_zext<64,6>(add_ln321_fu_198_p2.read());
}

void MixColumns::thread_zext_ln321_2_fu_336_p1() {
    zext_ln321_2_fu_336_p1 = esl_zext<6,5>(tmp_5_fu_328_p3.read());
}

void MixColumns::thread_zext_ln321_3_fu_345_p1() {
    zext_ln321_3_fu_345_p1 = esl_zext<64,6>(add_ln321_1_fu_340_p2.read());
}

void MixColumns::thread_zext_ln321_fu_194_p1() {
    zext_ln321_fu_194_p1 = esl_zext<6,5>(tmp_4_fu_186_p3.read());
}

void MixColumns::thread_zext_ln99_fu_170_p1() {
    zext_ln99_fu_170_p1 = esl_zext<6,3>(c_0_reg_69.read());
}

void MixColumns::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln97_fu_158_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln99_fu_174_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_block_state5_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln106_fu_316_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

