// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "SubBytes.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic SubBytes::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic SubBytes::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> SubBytes::ap_ST_fsm_state1 = "1";
const sc_lv<5> SubBytes::ap_ST_fsm_state2 = "10";
const sc_lv<5> SubBytes::ap_ST_fsm_state3 = "100";
const sc_lv<5> SubBytes::ap_ST_fsm_state4 = "1000";
const sc_lv<5> SubBytes::ap_ST_fsm_state5 = "10000";
const sc_lv<32> SubBytes::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> SubBytes::ap_const_lv32_1 = "1";
const sc_lv<1> SubBytes::ap_const_lv1_0 = "0";
const sc_lv<32> SubBytes::ap_const_lv32_2 = "10";
const sc_lv<32> SubBytes::ap_const_lv32_3 = "11";
const sc_lv<3> SubBytes::ap_const_lv3_0 = "000";
const sc_lv<1> SubBytes::ap_const_lv1_1 = "1";
const sc_lv<32> SubBytes::ap_const_lv32_4 = "100";
const sc_lv<3> SubBytes::ap_const_lv3_4 = "100";
const sc_lv<3> SubBytes::ap_const_lv3_1 = "1";
const sc_lv<2> SubBytes::ap_const_lv2_0 = "00";
const bool SubBytes::ap_const_boolean_1 = true;

SubBytes::SubBytes(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sbox_V_U = new SubBytes_sbox_V("sbox_V_U");
    sbox_V_U->clk(ap_clk);
    sbox_V_U->reset(ap_rst);
    sbox_V_U->address0(sbox_V_address0);
    sbox_V_U->ce0(sbox_V_ce0);
    sbox_V_U->q0(sbox_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln544_fu_109_p2);
    sensitive << ( zext_ln80_reg_132 );
    sensitive << ( zext_ln544_1_fu_105_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln79_fu_69_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln79_fu_69_p2 );

    SC_METHOD(thread_c_fu_99_p2);
    sensitive << ( c_0_reg_58 );

    SC_METHOD(thread_icmp_ln79_fu_69_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_0_reg_47 );

    SC_METHOD(thread_icmp_ln80_fu_93_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( c_0_reg_58 );

    SC_METHOD(thread_r_fu_75_p2);
    sensitive << ( r_0_reg_47 );

    SC_METHOD(thread_sbox_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln544_fu_119_p1 );

    SC_METHOD(thread_sbox_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_state_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( state_V_addr_reg_145 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln544_2_fu_114_p1 );

    SC_METHOD(thread_state_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_state_V_d0);
    sensitive << ( sbox_V_q0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_state_V_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_tmp_fu_81_p3);
    sensitive << ( r_0_reg_47 );

    SC_METHOD(thread_zext_ln544_1_fu_105_p1);
    sensitive << ( c_0_reg_58 );

    SC_METHOD(thread_zext_ln544_2_fu_114_p1);
    sensitive << ( add_ln544_fu_109_p2 );

    SC_METHOD(thread_zext_ln544_fu_119_p1);
    sensitive << ( state_V_q0 );

    SC_METHOD(thread_zext_ln80_fu_89_p1);
    sensitive << ( tmp_fu_81_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln79_fu_69_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln80_fu_93_p2 );

    ap_CS_fsm = "00001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "SubBytes_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, state_V_address0, "(port)state_V_address0");
    sc_trace(mVcdFile, state_V_ce0, "(port)state_V_ce0");
    sc_trace(mVcdFile, state_V_we0, "(port)state_V_we0");
    sc_trace(mVcdFile, state_V_d0, "(port)state_V_d0");
    sc_trace(mVcdFile, state_V_q0, "(port)state_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, sbox_V_address0, "sbox_V_address0");
    sc_trace(mVcdFile, sbox_V_ce0, "sbox_V_ce0");
    sc_trace(mVcdFile, sbox_V_q0, "sbox_V_q0");
    sc_trace(mVcdFile, r_fu_75_p2, "r_fu_75_p2");
    sc_trace(mVcdFile, r_reg_127, "r_reg_127");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln80_fu_89_p1, "zext_ln80_fu_89_p1");
    sc_trace(mVcdFile, zext_ln80_reg_132, "zext_ln80_reg_132");
    sc_trace(mVcdFile, icmp_ln79_fu_69_p2, "icmp_ln79_fu_69_p2");
    sc_trace(mVcdFile, c_fu_99_p2, "c_fu_99_p2");
    sc_trace(mVcdFile, c_reg_140, "c_reg_140");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, state_V_addr_reg_145, "state_V_addr_reg_145");
    sc_trace(mVcdFile, icmp_ln80_fu_93_p2, "icmp_ln80_fu_93_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, r_0_reg_47, "r_0_reg_47");
    sc_trace(mVcdFile, c_0_reg_58, "c_0_reg_58");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, zext_ln544_2_fu_114_p1, "zext_ln544_2_fu_114_p1");
    sc_trace(mVcdFile, zext_ln544_fu_119_p1, "zext_ln544_fu_119_p1");
    sc_trace(mVcdFile, tmp_fu_81_p3, "tmp_fu_81_p3");
    sc_trace(mVcdFile, zext_ln544_1_fu_105_p1, "zext_ln544_1_fu_105_p1");
    sc_trace(mVcdFile, add_ln544_fu_109_p2, "add_ln544_fu_109_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

SubBytes::~SubBytes() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sbox_V_U;
}

void SubBytes::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_69_p2.read(), ap_const_lv1_0))) {
        c_0_reg_58 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        c_0_reg_58 = c_reg_140.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_fu_93_p2.read(), ap_const_lv1_1))) {
        r_0_reg_47 = r_reg_127.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        r_0_reg_47 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        c_reg_140 = c_fu_99_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        r_reg_127 = r_fu_75_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_fu_93_p2.read()))) {
        state_V_addr_reg_145 =  (sc_lv<4>) (zext_ln544_2_fu_114_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln79_fu_69_p2.read(), ap_const_lv1_0))) {
        zext_ln80_reg_132 = zext_ln80_fu_89_p1.read();
    }
}

void SubBytes::thread_add_ln544_fu_109_p2() {
    add_ln544_fu_109_p2 = (!zext_ln80_reg_132.read().is_01() || !zext_ln544_1_fu_105_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln80_reg_132.read()) + sc_biguint<6>(zext_ln544_1_fu_105_p1.read()));
}

void SubBytes::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void SubBytes::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void SubBytes::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void SubBytes::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void SubBytes::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void SubBytes::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln79_fu_69_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void SubBytes::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void SubBytes::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_69_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void SubBytes::thread_c_fu_99_p2() {
    c_fu_99_p2 = (!c_0_reg_58.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(c_0_reg_58.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void SubBytes::thread_icmp_ln79_fu_69_p2() {
    icmp_ln79_fu_69_p2 = (!r_0_reg_47.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(r_0_reg_47.read() == ap_const_lv3_4);
}

void SubBytes::thread_icmp_ln80_fu_93_p2() {
    icmp_ln80_fu_93_p2 = (!c_0_reg_58.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_58.read() == ap_const_lv3_4);
}

void SubBytes::thread_r_fu_75_p2() {
    r_fu_75_p2 = (!r_0_reg_47.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(r_0_reg_47.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void SubBytes::thread_sbox_V_address0() {
    sbox_V_address0 =  (sc_lv<8>) (zext_ln544_fu_119_p1.read());
}

void SubBytes::thread_sbox_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sbox_V_ce0 = ap_const_logic_1;
    } else {
        sbox_V_ce0 = ap_const_logic_0;
    }
}

void SubBytes::thread_state_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        state_V_address0 = state_V_addr_reg_145.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        state_V_address0 =  (sc_lv<4>) (zext_ln544_2_fu_114_p1.read());
    } else {
        state_V_address0 = "XXXX";
    }
}

void SubBytes::thread_state_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        state_V_ce0 = ap_const_logic_1;
    } else {
        state_V_ce0 = ap_const_logic_0;
    }
}

void SubBytes::thread_state_V_d0() {
    state_V_d0 = sbox_V_q0.read();
}

void SubBytes::thread_state_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        state_V_we0 = ap_const_logic_1;
    } else {
        state_V_we0 = ap_const_logic_0;
    }
}

void SubBytes::thread_tmp_fu_81_p3() {
    tmp_fu_81_p3 = esl_concat<3,2>(r_0_reg_47.read(), ap_const_lv2_0);
}

void SubBytes::thread_zext_ln544_1_fu_105_p1() {
    zext_ln544_1_fu_105_p1 = esl_zext<6,3>(c_0_reg_58.read());
}

void SubBytes::thread_zext_ln544_2_fu_114_p1() {
    zext_ln544_2_fu_114_p1 = esl_zext<64,6>(add_ln544_fu_109_p2.read());
}

void SubBytes::thread_zext_ln544_fu_119_p1() {
    zext_ln544_fu_119_p1 = esl_zext<64,8>(state_V_q0.read());
}

void SubBytes::thread_zext_ln80_fu_89_p1() {
    zext_ln80_fu_89_p1 = esl_zext<6,5>(tmp_fu_81_p3.read());
}

void SubBytes::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln79_fu_69_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln80_fu_93_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

}

